name: Build README
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.2.4
        with:
          description: |
            학습 조각 모음 Today I Learned
          footer: |
            [1]: https://simonwillison.net/2020/Apr/20/self-rewriting-readme/
            [2]: https://github.com/jbranchaud/til
          # list_most_recent: 2
          date_format: "2020 Jan 15:04"
